### ISSUE TITLE
Qubit Breadcrumb mapper crashes if no uv->page object is present

### ISSUE THREAD

**Issue by Craig-Qubit** [QubitProducts/opentag-library-sdk#33]
Sometimes we have QTracker depending on the Breadcrumb mapper and if it crashes then QTracker never loads for the page. We could add a filter to the tag to not fire without uv->page but that still means no QTracker. 

Solution proposed: update tag to check for page object and if not present then safely return.

**Comment by alexolivier** [comment]
https://github.com/QubitProducts/opentag-library-sdk/pull/34

**Comment by Craig-Qubit** [comment]
Fix deployed
