### ISSUE TITLE
errors / conf ?

### ISSUE THREAD

**Issue by kendrick-k** [QubitProducts/opentag-library-sdk#48]
Need some help, I have these errors on http://localhost:8888/shared/bin/html/index.html?1442851473962 :

* Error loading tag: Error loading tag: TypeError: Cannot set property 'versionClassPath' of undefined
* Error while executing configuration:TypeError: Cannot read property '_CONSTRUCTOR' of undefined
* Running build in background...Rebuild failed! {fail: "location does not exists: libraries/outbrain/visualrevenue"}
* Make sure that CLASSPATH of your library matches its location!

Last one in Java conf I suppose, does the other errors are due to this or something else ?

Thanks

**Comment by peterfronc** [comment]
can you push the fork and show your class? Did you use wizard?

That error basically means you have bad syntax or incorrect library definition.

**Comment by kendrick-k** [comment]
weird, your user appeared in the browser view : /Users/piotrfronc/dev/opentag-library-... but I can't find it in the code.

https://github.com/kendrick-k/opentag-library-sdk

**Comment by kendrick-k** [comment]
shared/bin/add-library.sh (& once java -jar shared/bin/LibraryWizard.jar --wizard, by error (I'm on linux))

**Comment by kendrick-k** [comment]
this is missing : http://localhost:8888/shared/bin/html/js/config.js

**Comment by peterfronc** [comment]
I have just pushed bugfixes. Try pulling from master repository.

**Comment by peterfronc** [comment]
The config.js is optional loader. It might be missing (it's normal), its used to redirect debug state in dev flow.

**Comment by kendrick-k** [comment]
thank you I synced it ! That works. If you have some indications for me to understand properly how to glue & use the tagsdk.js + the container & tags call + the libs. I can push you more tags.

**Comment by peterfronc** [comment]
There are some structural changes coming and opentag-v3 is actively developed, but basically, the libraries tree is a standard JS classes src tree. We use compilejs to fast way build any tree node (or generate paths index, you basically pass the tool some options and source set to build JS you can think of it as something similiar to sprockets but it is designed to work in java classpath sense, to check more just browse https://github.com/peterfronc/compilejs).
If you check TagSDK sources you will notice that library is in fact a tag class, and tags using it are either instances of its configuration or classes extending it. So once you understand how libraries work you dont need a wizard as its just a file with configuration passed, each configuration property (config, pre, post, script) will land on the object prototype.
In opentag-v3 branch you will be able to add more properties or even another source tree and just add it as a dependency with compilejs.
When you check on the properties - notice that same names are on the tag properties (see Opentag site).

**Comment by kendrick-k** [comment]
thanks, nice work.
