### ISSUE TITLE
Running tests : Variable Name: undefined, Exists: false

### ISSUE THREAD

**Issue by kendrick-k** [QubitProducts/opentag-library-sdk#52]
Hello, 

Running the library test on http://localhost:8888/shared/bin/html/index.html gives an error though the value setted & saved ( SmartAdServer domain (token: sas_domain) ), am I missing something ?

Is the file local/Config.js necessary (or generated by build) ?

FINE: Tag[SmartAdServer main script] ->  Variable Name: undefined, Exists: false, Token: sas_domain, Value:undefined

![Uploading library_run.jpg…]()

**Comment by peterfronc** [comment]
It basically means that page variable is unset. You can override value using the input in the form (it should be js expression) or setup UV with the uv button.
