### ISSUE TITLE
doc tagsdk/docs/template.html : getElementsById > getElementById

### ISSUE THREAD

**Issue by kendrick-k** [QubitProducts/opentag-library-sdk#53]
https://opentag.qubitproducts.com/tagsdk/docs/template.html#!/api/qubit.opentag.GenericLoader-cfg-locationPlaceHolder

Any other string value will resolve to document.getElement**s**ById(string)
=>
Any other string value will resolve to document.**getElementById**(string)

**Comment by kendrick-k** [comment]
@peterfronc documentation detail

**Comment by peterfronc** [comment]
Thanks for spotting! Documentation will be updated with upcoming release.
