### ISSUE TITLE
[Question] What is this for ?

### ISSUE THREAD

**Issue by Germanaz0** [QubitProducts/opentag-library-sdk#79]
I ran this package and I only see a page saying "Tag library testing page" (ran snowplowanalytics) I thought that it was something like https://opentag.qubitproducts.com/QDashboard/ or something similar.

So wanted to check if there is something else than "Tag library testing page" like a dashboard or something.

Thanks and sorry, probably the question is not the smartest one, but am confused

**Comment by mediafigaro** [comment]
Hello, it's a page to check the library in itself, the dashboard part is not opensourced. The only part you get here is the tag management JS front end logic and the library (tags & tests you saw).

**Comment by peterfronc** [comment]
This is the Opentag's libraries sdk repository. This repository is used to manage all tag libraries used in Opentag, to try it out, check out the repository and run build.sh on any libraries resource (any libraries/ sub-directory). Basically - if you like to add oe of libraries to our repository - this is the right place to fork.

If you want to look more into Opentag TagSDK API that this repository and the Opentag itself is based on - you may want to look into https://github.com/QubitProducts/OpenTag
